[env]
# Use vendored liboqs
OQS_FEATURES = "vendored"

# OpenSSL paths (macOS Homebrew)
OPENSSL_DIR = "/opt/homebrew/opt/openssl@3"
OPENSSL_LIB_DIR = "/opt/homebrew/opt/openssl@3/lib"
OPENSSL_INCLUDE_DIR = "/opt/homebrew/opt/openssl@3/include"
PKG_CONFIG_PATH = "/opt/homebrew/opt/openssl@3/lib/pkgconfig"
LIBRARY_PATH = "/opt/homebrew/opt/openssl@3/lib"
DYLD_LIBRARY_PATH = "/opt/homebrew/opt/openssl@3/lib"

